### PR TITLE
reduced enemy attacking interval from 3 to 8

### PR DESCRIPTION
**Pull request by dVoorhout**

### CODE REVIEW

**Comment by dVoorhout** [comment]
in seconds*

**Comment by LMiljak** [comment]
:+1: Based on input from other users we agreed that this is the best interval.

PS: You can edit your PR title.

**Comment by dVoorhout** [comment]
wow thanks Luka, I learn something new everyday with you

**Comment by NilsHullegien** [comment]
Good idea on changing the attack interval, it was indeed too fast before. I approve.

**Pull request merged**
