### PR TITLE
Improvement model moving obstacle

### PR DESCRIPTION
**Pull request by NilsHullegien**
The model for the moving obstacle is now a red slime that is facing you.

Note: Didn't realize that me changing the model scale caused tests to fail, the build is green now.

### CODE REVIEW

**Comment by LMiljak** [comment]
Could the model be a little bit bigger? They're hard to spot from a distance. But maybe that's just because I'm testing without the Oculus Rift.

**Comment by NilsHullegien** [comment]
Will do! 
Closing PR for now.

**Comment by NilsHullegien** [comment]
Obstacles are bigger now!
Reopening PR

**Comment by LMiljak** [comment]
Looks good now.

**Comment by dVoorhout** [comment]
Seems to work fine, I approve

**Pull request merged**
