### PR TITLE
Improvement enemy model

### PR DESCRIPTION
**Pull request by NilsHullegien**
The enemies are now slimes. 
NOTE: I am aware that the models are clipping with the carriers, this will be fixed in another PR.

### CODE REVIEW

**Comment by NilsHullegien** [comment]
Whoops, forgot to remove the carriers for testing, will do that now. Closing.

**Comment by NilsHullegien** [comment]
Removed the carriers, reopening.

**Comment by NilsHullegien** [comment]
I am the biggest pancake ever, did the same thing i did with the pr of the platform............
Fixing it right now, closing PR.

**Comment by NilsHullegien** [comment]
Fixed the mistake, reopening pr

**Comment by LMiljak** [comment]
I approve. Let's just hope Mojang doesn't sue us.

**Comment by marcelkuipers** [comment]
Model seem to be very small. It would be nice to make them a bit larger.

**Comment by NilsHullegien** [comment]
Will do, they are indeed way to small.
Closing PR for now.

**Comment by NilsHullegien** [comment]
I scaled the model so now it is well visible. As the pr description says, I am aware that the enemy is clipping with the enemies and the platform. This will be fixed in another branch.
Reopening

**Comment by NilsHullegien** [comment]
Closing PR to fix travis build

**Comment by NilsHullegien** [comment]
Failing build is fixed now, reopening PR.

**Comment by marcelkuipers** [comment]
Looking good now. Merging.

**Pull request merged**
