### PR TITLE
Android app setup

### PR DESCRIPTION
**Pull request by marcelkuipers**
In this pull request the project is changed into a modular maven project.
A working version of a basic Android app is also implemented

### CODE REVIEW

**Comment by LMiljak** [comment]
At long last.
However, the ServerFinder and ServerDiscoveryHandler classes are still in a redundant package. I can quickly move those.

**Comment by LMiljak** [comment]
Oh also, the lambda expressions are still commented out. That also needs to be fixed before merging. I'll do that as well.

**Comment by LMiljak** [comment]
Ok, now I approve! Waiting for one more approval.

**Comment by dVoorhout** [comment]
For some files that have been automatically generated it is unclear what their exact purpose is. I understand this not your fault, but I think it's important we do some research on them. Everything looks fine.

**Pull request merged**
