### PR TITLE
Feature return to menu

### PR DESCRIPTION
**Pull request by marcelkuipers**
You can now press E to return to the main menu.

### CODE REVIEW

**Comment by NilsHullegien** [comment]
Looks good to me!

**Comment by dVoorhout** [comment]
The code looks fine but there seems to be a memory leak when restarting the game many times, about 30/40 MB each time.

**Comment by marcelkuipers** [comment]
Good call! Memory clearing seems to take place sometimes, but I can't really control when it happens. I will close this PR and try and fix it.

**Comment by marcelkuipers** [comment]
I now made sure that the assetManager gets cleared, which mostly solved the problem

**Comment by NilsHullegien** [comment]
I still approve of this code.

**Comment by dVoorhout** [comment]
The memory leak seems to be fixed, mostly, I'll merge it

**Pull request merged**
