### PR TITLE
Bugfix flycamera

### PR DESCRIPTION
**Pull request by LMiljak**
Re-added/refactored/fixed the fly camera.
It now uses a MoveBehaviour and a RotateBehaviour.

### CODE REVIEW

**Comment by dVoorhout** [comment]
Please add javadoc to the methods

**Comment by LMiljak** [comment]
Added it.

**Comment by LMiljak** [comment]
Closing until merge conflict has been resolved.

**Comment by LMiljak** [comment]
Fixed merge conflict. Reopening.

**Comment by dVoorhout** [comment]
looks good

**Comment by ThatFlint** [comment]
Damian, you were the first to approve here :P

**Comment by ThatFlint** [comment]
It's okay though, I approve too :+1:

**Pull request merged**
