### PR TITLE
Moving obstacles

### PR DESCRIPTION
**Pull request by marcelkuipers**
This PR implements moving obstacles.
Right now, the ObstacleSpawner only spawns MovingObstacles. If you want to change back to StaticObstacles you instanciate the ObstacleFactory with a new StaticObstacleFactory

### CODE REVIEW

**Comment by NilsHullegien** [comment]
Looks good to me!

**Comment by LMiljak** [comment]
In the MovingObstacleMoveBehaviour, you make use of a private Vector3f moveVector and you return it in the overridden getMoveVector(). Can't you use the moveVector of the superclass? So just use setMoveVector and the getMoveVector of the superclass.

**Comment by marcelkuipers** [comment]
You were correct about using the superclass method. I fixed it now.

**Comment by LMiljak** [comment]
Sorry about the late reply.
It looks good now :+1: 
Merging

**Pull request merged**
