### PR TITLE
Sprint backlog #1 + top3

### PR DESCRIPTION
**Pull request by NilsHullegien**
Added both documents in a deliverables map

### CODE REVIEW

**Comment by LMiljak** [comment]
Please include the deliverables somewhere in your repositories (these should be public!) 
**and put a link to the file in the README that is in the root of the repo (so that we can find them easily).**

**Comment by NilsHullegien** [comment]
Added a link in the readme, this link will work after merge, since in this version of the master there is no deliverables folder.

**Comment by LMiljak** [comment]
╱╱┏╮
╱╱┃┃
/ ▉━╯┗━╮
/ ▉┈┈┈┈┃
/╱╰━━━╯

**Comment by ThatFlint** [comment]
's okay

**Pull request merged**
