### PR TITLE
Main menu pc

### PR DESCRIPTION
**Pull request by NilsHullegien**
Adds the main menu for the game, as well as the VR support in the game. 
PLEASE test the code as well, had to fix some merge conflicts that affected both pom.xml files.

### CODE REVIEW

**Comment by dVoorhout** [comment]
looks good

**Comment by ThatFlint** [comment]
:+1:

**Comment by NilsHullegien** [comment]
@ThatFlint next time, when you are the second person to accept a PR, please merge as well.

**Comment by ThatFlint** [comment]
Oh whoops
I went to have dinner x)

**Comment by NilsHullegien** [comment]
All good x)

**Pull request merged**
