### PR TITLE
Updated EAD with some class diagrams

### PR DESCRIPTION
**Pull request by LMiljak**
I have made more diagrams (for the obstacles, enemies, levelgenerators, messagelisteners) but decided to exclude those as they contain ideas for the refactoring of next sprint.

### CODE REVIEW

**Comment by NilsHullegien** [comment]
4.4 and 4.5 have the same title, while 4.4 has text and 4.5 appears to be unused.
We will probably want 4.5 to be removed.

**Comment by LMiljak** [comment]
@NilsHullegien 4.5 appears to be unused? The class diagrams are located there. I just forgot to give 4.5 a proper name. I'm fixing that now.

**Comment by LMiljak** [comment]
Oh I see, Google Docs doesn't like being exported as a PDF...

**Comment by NilsHullegien** [comment]
Ok, when I looked at it it looked like the diagrams were like appendices. Looking at it again I realized I was wrong, sorry about that.

**Comment by LMiljak** [comment]
Fixed it :+1:

**Comment by NilsHullegien** [comment]
Looks good now!

**Comment by NilsHullegien** [comment]
Merging

**Pull request merged**
