### PR TITLE
Feature server not found

### PR DESCRIPTION
**Pull request by ThatFlint**
When the client can't connect to the server, it is closed and a popup appears, telling the player what to do, namely having the game turned on before starting the app.

This replaces app states (loading screens, etc.) cause the autoconnector seemed to prevent views from being shown on the screen and it would take too long to figure it out.

### CODE REVIEW

**Comment by dVoorhout** [comment]
checkstyle: unused imports in both files

**Comment by dVoorhout** [comment]
and i accidentally merged the master into this branch, but that's okay ;p

**Comment by ThatFlint** [comment]
Should now be mergeable

**Comment by LMiljak** [comment]
Please merge master into this branch :) because another PR has been accepted and merging may detect certain errors.

**Comment by LMiljak** [comment]
Code looks good though, I approve

**Comment by LMiljak** [comment]
:+1:  Merging

**Pull request merged**
