### PR TITLE
Feature platform texture

### PR DESCRIPTION
**Pull request by NilsHullegien**
Added a texture to our platform.

### CODE REVIEW

**Comment by NilsHullegien** [comment]
Closing the PR since the platform isnt visible at all, must have messed something up

**Comment by NilsHullegien** [comment]
Made a really stupid mistake, the platform is visible now.

**Comment by dVoorhout** [comment]
everything seems to work now, code looks fine

**Comment by marcelkuipers** [comment]
It looks fine. Merging.

**Pull request merged**
