### PR TITLE
TRAVIS WORKS TRAVIS WORKS TRAVIS WORKS TRAVIS WORKS TRAVIS WORKS!

### PR DESCRIPTION
**Pull request by LMiljak**
I don't care that this PR message is informal. Im just glad this is finally done.

### CODE REVIEW

**Comment by LMiljak** [comment]
FYI, try not to make too much sense out of the commits. It was mostly trial&error.
The main fix is in creating the repositories local.

**Comment by NilsHullegien** [comment]
Good job!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Green build again on master :+1: :+1: :+1:

**Comment by ThatFlint** [comment]
Awesome!

**Comment by LMiljak** [comment]
Remi you pancake

**Comment by ThatFlint** [comment]
I waited til both checks were green, honest x)

**Pull request merged**
